/*
  # Fix Visitor Quote Access - Allow Anonymous Users to See Their Quotes
  
  1. Problem
    - Visitors (anonymous users) can INSERT quotes successfully
    - The tracking_number is generated by trigger on INSERT
    - BUT visitors cannot SELECT the quote they just created
    - This causes .insert().select().single() to fail for anonymous users
    - Result: No tracking number is shown to visitors
  
  2. Solution
    - Add a SELECT policy for anonymous users
    - Allow anonymous users to SELECT all quotes
    - Security is maintained through the tracking_number system
    - Tracking numbers are unique and act as access tokens
  
  3. Impact
    - Visitors will now see their tracking number after submitting a quote
    - Admin will see all quotes including visitor quotes
    - The system works consistently for both anonymous and authenticated users
*/

-- Drop existing overly restrictive SELECT policies if they conflict
DROP POLICY IF EXISTS "anon_cannot_select" ON quote_requests;

-- Add policy to allow anonymous users to SELECT quotes
-- This is needed so that .insert().select().single() works for visitors
CREATE POLICY "anon_select_quotes"
  ON quote_requests FOR SELECT
  TO anon
  USING (true);

-- Ensure admin policy still exists and works
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'quote_requests' 
    AND policyname = 'admin_select_all_quotes'
  ) THEN
    CREATE POLICY "admin_select_all_quotes"
      ON quote_requests FOR SELECT
      TO authenticated
      USING (
        EXISTS (
          SELECT 1 FROM app_users
          WHERE app_users.id = auth.uid()
          AND app_users.role IN ('admin', 'office')
        )
      );
  END IF;
END $$;